#Clinical Research

##Manipulating Data with Pandas

>By Nicolas Almeida

###Libraries

In [84]:
import pandas as pd #Importing pandas

In [85]:
import numpy as np #Importing numpy

In [86]:
from google.colab import drive #Importing drive

In [87]:
#Format tables printed to the screen
%load_ext google.colab.data_table

The google.colab.data_table extension is already loaded. To reload it, use:
  %reload_ext google.colab.data_table

###Data Import

In [88]:
#Importing data from Github
url = 'https://raw.githubusercontent.com/nicolas-almeida-v/pandas-data-cleaning-us-surgery/main/surgery.csv'
df = pd.read_csv(url)

I have already uploaded the dataset in GitHub. So I just used the raw link to reference the dataset.

In [89]:
type(df) #Type of object in the data frame

pandas.core.frame.DataFrame

In [90]:
df.head() #Initial inspection of data

,City,Procedure,Number of Surgeons,Price Range,Average Price,Top Rated Surgeon,More Information
0,Tampa,Tummy Tuck,419,"$7,000 to $14,000","$7,600",Dr. John Roach,https://www.aestheticmatch.com/cities/tampa
1,Tampa,Breast Reduction,169,"$6,000 to $11,200","$11,350","Dr. Traci Temmen, MD",https://www.aestheticmatch.com/cities/tampa
2,Tampa,Liposuction,156,"$4,000 to $11,000","$8,000",Dr. Traci Temmen,https://www.aestheticmatch.com/cities/tampa
3,Tampa,Breast Implants,152,"$4,500 - $6,500","$5,700",Dr. Jaime Perez,https://www.aestheticmatch.com/cities/tampa
4,Tampa,Facelift,147,"$8,900 - $17,000","$12,300","Dr. Demetri Arnaoutakis, MD",https://www.aestheticmatch.com/cities/tampa

In [91]:
df.shape #Number of rows and columns of the data frame

(600, 7)

In [92]:
df.columns #Description of columns

Index(['City', 'Procedure', 'Number of Surgeons', 'Price Range',
       'Average Price', 'Top Rated Surgeon', 'More Information'],
      dtype='object')

In [93]:
df.size #Total number of point values (rows x columns)

4200

In [94]:
df.dtypes #Types of data for each column

City                  object
Procedure             object
Number of Surgeons     int64
Price Range           object
Average Price         object
Top Rated Surgeon     object
More Information      object
dtype: object

At this point I see that Average Price is an object (str). This is because Pandas reads $ and comma (,) as string; so now I am converting into float to later perform mathematical calculations. I am pretty sure that I will make some changes to the data types further, but for now changing Average Price is good for me.

In [95]:
df['Average Price'] = df['Average Price'].replace('[\$,]','',regex=True).astype(float) #Remove dollar sign and commas, then convert to float

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipython-input-201/1454859589.py:1: SyntaxWarning: invalid escape sequence '\$'
  df['Average Price'] = df['Average Price'].replace('[\$,]','',regex=True).astype(float) #Remove dollar sign and commas, then convert to float

In [96]:
df.rename(columns={'Average Price':'Average Price ($)'}, inplace=True) #Renaming column

In [97]:
df.head()

,City,Procedure,Number of Surgeons,Price Range,Average Price ($),Top Rated Surgeon,More Information
0,Tampa,Tummy Tuck,419,"$7,000 to $14,000",7600.0,Dr. John Roach,https://www.aestheticmatch.com/cities/tampa
1,Tampa,Breast Reduction,169,"$6,000 to $11,200",11350.0,"Dr. Traci Temmen, MD",https://www.aestheticmatch.com/cities/tampa
2,Tampa,Liposuction,156,"$4,000 to $11,000",8000.0,Dr. Traci Temmen,https://www.aestheticmatch.com/cities/tampa
3,Tampa,Breast Implants,152,"$4,500 - $6,500",5700.0,Dr. Jaime Perez,https://www.aestheticmatch.com/cities/tampa
4,Tampa,Facelift,147,"$8,900 - $17,000",12300.0,"Dr. Demetri Arnaoutakis, MD",https://www.aestheticmatch.com/cities/tampa

###Extracting rows and Columns

Below, we extract the column 'Number of Surgeons' and save it as an object in order to perform analysis on an individual column.

In [98]:
number_of_surgeons = df['Number of Surgeons'] #Extracting column

In [99]:
type(number_of_surgeons) #Type of object --> series object

pandas.core.series.Series

In [100]:
number_of_surgeons.head() #Head of the column

0    419
1    169
2    156
3    152
4    147
Name: Number of Surgeons, dtype: int64

In [101]:
number_of_surgeons.min() #What is the minimum value in Number of Surgeons

0

In [102]:
df[df['Number of Surgeons'] == 0] #I wanted to know which rows held the 0 number of surgeons

,City,Procedure,Number of Surgeons,Price Range,Average Price ($),Top Rated Surgeon,More Information
135,Austin,Tummy Tuck,0,"$8,000 to $15,000",12200.0,Dr. Aisha White,https://www.aestheticmatch.com
188,Laredo,Nose Plastic Surgery (Rhinoplasty),0,"$4,000 to $16,000",7800.0,Dr. Jose Barrera,https://www.aestheticmatch.com
202,Frisco,Nose Plastic Surgery (Rhinoplasty),0,"$7,000 to $20,000",11150.0,Dr. Sean Hill,https://www.aestheticmatch.com
226,Austin,Nose Plastic Surgery (Rhinoplasty),0,"$6,000 – $17,000",15890.0,"Dr. Louis William Apostolakis, M.D.",https://www.aestheticmatch.com
250,Richmond,Liposuction,0,"$2,000 to $7,500",3700.0,Dr. Neil Zemmel,https://www.aestheticmatch.com
280,Laredo,Liposuction,0,"$10,000 to $16,000",12900.0,Laredo Wellness and Aesthetics,https://www.aestheticmatch.com
289,Henderson,Liposuction,0,"$3,900 to $20,000",12200.0,Dr. Shahin Ghadir,https://www.aestheticmatch.com
292,Gilbert,Liposuction,0,"$2,000 to $18,000",11850.0,"Dr. Jude LaBarbera, MD",https://www.aestheticmatch.com
294,Frisco,Liposuction,0,"$3,600 - $8,500",4100.0,Dr. Raja Mohan,https://www.aestheticmatch.com
318,Austin,Liposuction,0,"$3,000 to $9,800",5900.0,"Dr. Justin West, MD",https://www.aestheticmatch.com
342,Richmond,Facelift,0,"$7,000 to $15,000+",11750.0,Dr. Mark Zinsser,https://www.aestheticmatch.com
360,Nashville,Facelift,0,"$9,800 to $21,000",14200.0,Dr. David Gilpin,https://www.aestheticmatch.com
372,Laredo,Facelift,0,"$7,000 to $20,000",9100.0,"Dr. Marco R. Avila, MD",https://www.aestheticmatch.com
381,Henderson,Facelift,0,"$6,000 to $30,000",18150.0,Dr. Jeffrey Roth,https://www.aestheticmatch.com
384,Gilbert,Facelift,0,"$7,500 to $35,000",17800.0,Dr. Todd Hobgood,https://www.aestheticmatch.com
386,Frisco,Facelift,0,"$3,500 - $15,000",8500.0,Dr. Ken Smart,https://www.aestheticmatch.com
410,Austin,Facelift,0,"$8,000 to $45,000",12800.0,Dr. Holzman (Holzman Plastic Surgery),https://www.aestheticmatch.com
464,Laredo,Breast Reduction,0,"$4,666 to $11,442",7620.0,Alamo Plastic Surgery,https://www.aestheticmatch.com
478,Frisco,Breast Reduction,0,"$6,500 to $13,500",9600.0,"Dr. Ken Smart, MD",https://www.aestheticmatch.com
502,Austin,Breast Reduction,0,"$5,500 to $14,500",8700.0,Dr. Aisha D. White,https://www.aestheticmatch.com
526,Richmond,Breast Implants,0,"$5,000 to $8,200+",8036.0,"Dr. Sundin, Virginia Institute of Plastic Surgery",https://www.aestheticmatch.com
534,Philadelphia,Breast Implants,0,"$8,000 - $11,000",9950.0,Dr. Bottger,https://www.aestheticmatch.com
544,Nashville,Breast Implants,0,"$5,900 – $9,500",7730.0,Dr. Brian P. Tierney,https://www.aestheticmatch.com
556,Laredo,Breast Implants,0,5000-8000,5700.0,"Dr. Lance Troell, MD",https://www.aestheticmatch.com
570,Frisco,Breast Implants,0,"$5,000 to $7,900",6650.0,"Dr. Ken Smart, MD",https://www.aestheticmatch.com
594,Austin,Breast Implants,0,"$5,500 - $10,000",6700.0,"Dr. Steven Camp, MD",https://www.aestheticmatch.com

In [103]:
(df['Number of Surgeons']==0).sum() #How many rows held 0 Number of Surgeons

np.int64(26)

In [104]:
number_of_surgeons.max() #What is the maximum value in Number of Surgeons

1878

In [105]:
number_of_surgeons.mean() #What is the mean value in Number of Surgeons

np.float64(128.15)

In order to extract information from a row with .iloc[] function

In [106]:
df.iloc[0] #Information of row 0

City                                                        Tampa
Procedure                                              Tummy Tuck
Number of Surgeons                                            419
Price Range                                     $7,000 to $14,000
Average Price ($)                                          7600.0
Top Rated Surgeon                                  Dr. John Roach
More Information      https://www.aestheticmatch.com/cities/tampa
Name: 0, dtype: object

In [107]:
df.iloc[[2,50,100]] #Information of row 2, 50 and 100

,City,Procedure,Number of Surgeons,Price Range,Average Price ($),Top Rated Surgeon,More Information
2,Tampa,Liposuction,156,"$4,000 to $11,000",8000.0,Dr. Traci Temmen,https://www.aestheticmatch.com/cities/tampa
50,Virginia Beach,Tummy Tuck,145,"$6,000 to $15,000",9100.0,Dr. Michael J. Zaremba,https://www.aestheticmatch.com
100,Jacksonville,Tummy Tuck,97,"$8,000 to $16,000",10200.0,Dr. Patrick Basile,https://www.aestheticmatch.com

In [108]:
df.iloc[0:5] #Information of rows 0 to 4

,City,Procedure,Number of Surgeons,Price Range,Average Price ($),Top Rated Surgeon,More Information
0,Tampa,Tummy Tuck,419,"$7,000 to $14,000",7600.0,Dr. John Roach,https://www.aestheticmatch.com/cities/tampa
1,Tampa,Breast Reduction,169,"$6,000 to $11,200",11350.0,"Dr. Traci Temmen, MD",https://www.aestheticmatch.com/cities/tampa
2,Tampa,Liposuction,156,"$4,000 to $11,000",8000.0,Dr. Traci Temmen,https://www.aestheticmatch.com/cities/tampa
3,Tampa,Breast Implants,152,"$4,500 - $6,500",5700.0,Dr. Jaime Perez,https://www.aestheticmatch.com/cities/tampa
4,Tampa,Facelift,147,"$8,900 - $17,000",12300.0,"Dr. Demetri Arnaoutakis, MD",https://www.aestheticmatch.com/cities/tampa

In [109]:
df.iloc[0:5, [0,4]] #Information of row 1 to 4, but only for variables 0 (City) and 4 (Average Price ($))

    City  Average Price ($)
0  Tampa             7600.0
1  Tampa            11350.0
2  Tampa             8000.0
3  Tampa             5700.0
4  Tampa            12300.0

*   .iloc[] (used for integers)
*   .loc[] (can use str)

In [110]:
df.loc[0:5, ['City','Average Price ($)']] #Information of row 1 to 4, but only for variables 'City' and 'Average Price ($)' / Same as above but str were used instead of int

    City  Average Price ($)
0  Tampa             7600.0
1  Tampa            11350.0
2  Tampa             8000.0
3  Tampa             5700.0
4  Tampa            12300.0
5  Tampa            10400.0

The .iat[] property extracts a single cell by using its row and column index.

In [111]:
df.iat[2,3] #Extract cell information of row 2 and column 3

'$4,000 to $11,000'

The .at[] property does the same, but we can specify labels.

In [112]:
df.at[2,'Price Range'] #Extract the same as above but used str instead of int

'$4,000 to $11,000'

###Filtering Data

#####Find all unique values in a column

The .unique() method is used to find all the sample space elements in a column.

In [113]:
df.Procedure.unique() #To find values included in the columns (removing duplicates)

array(['Tummy Tuck', 'Breast Reduction', 'Liposuction', 'Breast Implants',
       'Facelift', 'Nose Plastic Surgery (Rhinoplasty)'], dtype=object)

####Filtering 2 variables: What is the average price of all procedures in Tampa?

Create an array that contains the Average price ($) of each procedure in the City of Tampa

In [114]:
average_price_tampa = df.loc[df['City'] == 'Tampa']['Average Price ($)'].to_numpy()

In [115]:
average_price_tampa.mean() #Average price of all procedures in Tampa

np.float64(9225.0)

####Filtering 3 variables with 'and' (&): What is the average price of facelifts done in cities where there are 500 surgeons or more?

The symbol for and is & and for or is |.

In [116]:
price_facelifts_500_more_surgeons=df.loc[(df['Number of Surgeons']>=500) & (df['Procedure']=='Facelift')]['Average Price ($)'].to_numpy()

In [117]:
price_facelifts_500_more_surgeons.mean() #Average price of facelifts done in cities where there are 500 surgeons or more

np.float64(12213.333333333334)

In [118]:
int(price_facelifts_500_more_surgeons.mean()) #The same as above but integer instead of float

12213

####Filtering 3 variables with 'and' (&): What is the average price of facelifts done in cities where there are less than 500 surgeons?

In [119]:
crit = (df['Number of Surgeons']<500) & (df['Procedure']=='Facelift') #Creating the criteria variable to get a cleaner code

In [120]:
price_facelifts_500_less_surgeons=df.loc[crit]['Average Price ($)'].to_numpy()

In [121]:
price_facelifts_500_less_surgeons.mean() #Average price of facelifts done in cities where there are less than 500 surgeons

np.float64(14714.144329896908)

In [122]:
int(price_facelifts_500_less_surgeons.mean()) #The same as above but integer instead of float

14714

####Filtering 3 variables with 'or' (|): What is the average price of facelifts OR liposuction done in cities where there are 500 surgeons or more?

In [123]:
crit = (df['Number of Surgeons']>=500) & ((df['Procedure']=='Facelift') | (df['Procedure']=='Liposuction')) #Creating the criteria variable to get a cleaner code

In [124]:
price_facelits_or_liposuction_500_more_surgeons=df.loc[crit]['Average Price ($)'].to_numpy()

In [125]:
int(price_facelits_or_liposuction_500_more_surgeons.mean()) #Average price of facelifts or liposuctions in cities where there are less than 500 surgeons

7817

####Filtering 3 variables with 'negation' (~): What is the average price of procedures that are NOT facelifts NOR liposuction done in cities where there are 500 surgeons or more?

In [126]:
crit = (df['Number of Surgeons']>=500) & ~((df['Procedure']=='Facelift') | (df['Procedure']=='Liposuction'))

In [127]:
price_no_facelifts_nor_liposuction_500_more_surgeons=df.loc[crit]['Average Price ($)'].to_numpy()

In [128]:
int(price_no_facelifts_nor_liposuction_500_more_surgeons.mean()) #Average price of procedures that are NOT facelifts NOR liposuction done in cities where there are 500 surgeons or more

10523

###Creating a new dataframe object that only has an average price of less than $9000

This would be a sub-dataframe object because the information is based on the previous daataframe and must include all variables except that will only take those values linked to procedures with an average price of less than $9000

In [129]:
#Calculate and display the mean of the 'Average Price ($)' column
#I wanted to calculate this to get an idea of the range of prices
mean_average_price = df['Average Price ($)'].mean()
max = df['Average Price ($)'].max()
min = df['Average Price ($)'].min()
print(f"Average is: {mean_average_price}, max is: {max}, min is: {min}")

Average is: 9839.661666666667, max is: 45200.0, min is: 3100.0

In [130]:
new_df = df[df['Average Price ($)']<9000]

In [131]:
new_df.head()

,City,Procedure,Number of Surgeons,Price Range,Average Price ($),Top Rated Surgeon,More Information
0,Tampa,Tummy Tuck,419,"$7,000 to $14,000",7600.0,Dr. John Roach,https://www.aestheticmatch.com/cities/tampa
2,Tampa,Liposuction,156,"$4,000 to $11,000",8000.0,Dr. Traci Temmen,https://www.aestheticmatch.com/cities/tampa
3,Tampa,Breast Implants,152,"$4,500 - $6,500",5700.0,Dr. Jaime Perez,https://www.aestheticmatch.com/cities/tampa
6,Miami,Tummy Tuck,576,"$3,000 to $12,000",8072.0,Dr. K (DrKMiamiPlasticSurgery.com),https://www.aestheticmatch.com/cities/miami
7,Miami,Liposuction,323,"$1,500 to $10,000",3800.0,"Dr. Daniel K. Becker, MD, FACS",https://www.aestheticmatch.com/cities/miami

In [132]:
#Let's verify if this dataframe is correct by looking the maximum 'Average Price ($)'
new_df['Average Price ($)'].max()

8960.0

###Creating a new dataframe for patients with a restricted list of Cities

Up until now, we have had single values for our filter criteria. Here we  want to filter on more than one value, say *Seattle*, *Los Angeles*, and *Chicago*.  Here's how we would do that, by using the `isin()` method.

In [133]:
list_of_cities = ['Seattle','Los Angeles','Chicago']
crit = df['City'].isin(list_of_cities)

cities_df = df.loc[crit]
cities_df.head()

,City,Procedure,Number of Surgeons,Price Range,Average Price ($),Top Rated Surgeon,More Information
12,Los Angeles,Tummy Tuck,1081,"$4,000 to $20,000",15380.0,Dr. Stephen Bresnick,https://www.aestheticmatch.com/cities/los-angeles
13,Los Angeles,Breast Reduction,468,"$7,500 to $15,000",13900.0,Dr. Gary Motykie,https://www.aestheticmatch.com/cities/los-angeles
14,Los Angeles,Liposuction,422,"$2,000 to $40,000",6950.0,Dr. Sarah Yovino,https://www.aestheticmatch.com/cities/los-angeles
15,Los Angeles,Breast Implants,407,$7500-$12500,9100.0,Dr. David Stoker,https://www.aestheticmatch.com/cities/los-angeles
16,Los Angeles,Facelift,379,"$12,000 – $50,000",21500.0,Dr. Jay Calvert,https://www.aestheticmatch.com/cities/los-angeles

In [134]:
cities_df.tail() #Making sure the other cities were selected instead of just Los Angeles

,City,Procedure,Number of Surgeons,Price Range,Average Price ($),Top Rated Surgeon,More Information
400,Chicago,Facelift,133,"$3,800 to $21,000",7300.0,Northwestern Plastic Surgery,https://www.aestheticmatch.com
424,Seattle,Breast Reduction,119,"$7,800 to $9,000",8750.0,Dr. Jeffrey H. Barnett,https://www.aestheticmatch.com
492,Chicago,Breast Reduction,205,"$5,900 to $16,000",8300.0,Dr. Michael Horn,https://www.aestheticmatch.com
516,Seattle,Breast Implants,69,"$4,995 to $15,000",7200.0,Dr. Kris Day at Pacific Sound Plastic Surgery,https://www.aestheticmatch.com
584,Chicago,Breast Implants,160,"$6,995 to $25,000",8100.0,Dr. Michael Horn,https://www.aestheticmatch.com

###Create a new dataframe object where the Top Rated Surgeon is an institution instead of single surgeon (Does not have the term Dr or MD in it)

In [135]:
df['Top Rated Surgeon'].unique() #I was just checking what may differentiate between the column and realized that presence of Dr/MD could be a good variable to exclude

array(['Dr. John Roach', 'Dr. Traci Temmen, MD', 'Dr. Traci Temmen',
       'Dr. Jaime Perez', 'Dr. Demetri Arnaoutakis, MD',
       'Dr. Dominic Castellano', 'Dr. K (DrKMiamiPlasticSurgery.com)',
       'Dr. Daniel K. Becker, MD, FACS', 'Dr. K (Dr. K Plastic Surgery)',
       'Dr. Mel Ortega', 'Dr. Constantino Mendieta', 'Dr. Anthony Bared',
       'Dr. Stephen Bresnick', 'Dr. Gary Motykie', 'Dr. Sarah Yovino',
       'Dr. David Stoker', 'Dr. Jay Calvert', 'Dr. Babak Azizzadeh',
       'Dr. Christopher Patronella', 'Dr. Ahmadi', 'Dr. Ravi Somayazula',
       'Dr. Sameer Patel', 'Dr. Christopher Funk', 'Dr. Farris',
       'Dr. David Liland', 'Dr. Steve Liland', 'Dr. Paul Liland',
       'Dr. Michael Farris, MD', 'Dr. Jesse E. Smith, MD, FACS',
       'Dr. Thomas Yalif', 'Dr. Richard J. Arslanian',
       'Plastic Surgery Center of the South', 'Dr. Paul McCluskey',
       'Dr. Aaron Fletcher', 'Dr. Andrew M. Schneider, M.D., F.A.C.S.',
       'Dr. Matthew Conrad, MD', 'Salem Plastic Surgery',
       'Dr. Matthew Conrad, MD, PA', 'Dr. Sanjay Daluvoy',
       'Dr. Gilson J. Kingman', 'Dr. Charles Milliken',
       'Dr. James M. Shaw', 'Dr. James A. Rieger, MD', 'Dr. James Shaw',
       'Dr. Scott L. Tucker, MD', 'Dr. Matthew H. Conrad, MD',
       'Dr. Michael Weinfeld', 'Dr. Philip J. Miller',
       'Dr. Michael J. Zaremba', 'Dr. Brenda Schiesel', 'Dr. Scott Hurst',
       'Dr. John Zavell', 'Dr. Victor Mabourakh', 'Dr. John J. O’Brien',
       'Dr. Paul Rottler, MD', 'Dr. Kris Day', 'Dr. Anthony Tessler',
       'Dr. Wayne Yamahata', 'Dr. Alexander Ereso', 'Dr. Kimberly Henry',
       'Dr. Larry Pollack', 'Dr. Thomas Jeneby', 'Dr. Thao',
       'Dr. Ben Childers', 'Dr. Gordon Lewis', 'Dr. Timothy Janiga',
       'Dr. William Stoeckel', 'Dr. David Bohley', 'Dr. Lee',
       'Dr. Ronald M. Friedman, M.D.',
       'Dr. Wooten, Beleza Plastic Surgery',
       'Dr. William Hall, M.D. at Infini Phoenix Liposuction',
       'Dr. David Bottger', 'Dr. Jon Paul Trevisani', 'Dr. Ayoub',
       'Dr. Clinton Webster',
       'Dr. Wayne Yamahta, East Bay Plastic Surgery, Oakland, CA',
       'Dr. Joseph Stile', 'Dr. Sundin',
       'Dr. Joanna Partridge at Partridge Plastic Surgery',
       'Dr. Matthew Schulman, M.D.', 'Dr. Jules Walters', 'Dr. Harris',
       'Dr. Gregory T. Mesna', 'Dr. Mark Bonness',
       'Dr. Jude LaBarbera, MD', 'Dr. John Rosdeutscher',
       'Dr. Ember Ewings', 'Dr. Jane Rowley, Rowley Plastic Surgery',
       'Dr. Corbett', 'Dr. Naim', 'Dr. Jacobson', 'Dr. Jared Nimtz',
       'Dr. Bryson Richards', 'Dr. Nader Sukkar', 'Dr. Namrata Chhatre',
       'Dr. Pedy Ganchi, MD', 'Dr. Patrick Basile', 'Dr. Raja Mohan, MD',
       'Dr. Kimberly Short', 'Dr. Scott Ennis', 'Dr. Bernabe Vazquez',
       'Award-winning surgeons at H/K/B Cosmetic Surgery in Greensboro',
       'Dr. Vartany', 'Dr. Mark A. Chin, MD', 'Dr. Vishnu Rumalla',
       'Dr. Mark Jabor', 'Dr. William Ortiz', 'Dr. Repta',
       'Dr. R. Winfield Ketchum (Peak Plastic Surgery)',
       'Dr. Vijay Bindingnavele', 'Dr. Donaldson and Dr. Sieffert',
       'Dr. Steven Vath', 'Dr. Gregory M. Fedele, MD, FACS',
       'Dr. Loftus, Loftus Plastic Surgery Center',
       'Dr. Mark Mofid, MD, FACS', 'Dr. Laurie Casas',
       'Dr. Jon E. Paulk, MD (Norfolk Plastic Surgery)', 'Dr. Chad Deal',
       'Dr. Aldo Guerra', 'Dr. Robert Brueck', 'Dr. Samuel Shatkin Jr.',
       'Dr. Jeffrey Lee', 'Dr. Jonathan Kramer',
       'Dr. Ricardo L. Rodriguez', 'Dr. Mitts', 'Dr. Aisha White',
       'Dr. David Campbell', 'Dr. Michael J. Schoggen',
       'Dr. Saba Motakef, MD', 'Dr. Miguel Gallegos', 'Dr. William Choe',
       'Dr. Cuzalina', 'Dr. Jeffrey Nelson', 'Dr. John F. Zavell',
       'Dr. James W. Pearson, MD', 'Dr. Kevin Caceres',
       'Dr. Brian Ridenour, MD', 'Dr. Stile', 'Dr. Todd Hobgood',
       'Dr. Ali Sajjadian, MD', 'Dr. Larry Berkowitz', 'Dr. Mark Lee',
       'Dr. Roy David, MD', 'Dr. Constance Barone', 'Dr. Joe Gryskiewicz',
       'Dr. Ben Childers, MD', 'Dr. Burton M. Sundin, MD', 'Dr. Dayan',
       'Dr. Christopher D. Cohn at Specialists in Plastic Surgery, Raleigh',
       'Dr. Joseph Yocum', 'Lee Plastic Surgery', 'Dr. Wilcox',
       'Dr. Eric A. Pautler', 'Dr. Adrian Lo', 'Dr. Michael Gelineau',
       'Dr. Ayoub at Ayoub Plastic Surgery', 'Dr. James Lowe',
       'Dr. Rex Moulton-Barrett', 'Dr. Brian J. Parker',
       'Dr. John Steinmetz', 'Dr. Eric M. Joseph', 'Dr. David Cangello',
       'Dr. Charles G. Thorne', 'Dr. David Gilpin', 'Dr. Tholen',
       'Dr. Anand Patel', 'Dr. Robert Bonillas, MD',
       'Dr. Phillip Langsdon', 'Dr. Richard Parfitt',
       'Dr. Edward Daniele, MD', 'Dr. Lee Corbett', 'Dr. Kevin Sadati',
       'Dr. Jacobson, Jacobson Cosmetic Surgery', 'Dr. Jose Barrera',
       'Dr. Victor Perez, MD', 'Dr. Robert Morin',
       'Dr. David C. Pearson, M.D.', 'Dr. Babak Sadati',
       'Dr. Barry Eppley', 'Athena Clinic', 'Dr. Roland Hicks',
       'Dr. Eric J. Yavrouian', 'Dr. Josh Olson', 'Dr. Sean Hill',
       'Dr. Mark A. Chin, M.D.', 'Dr. Jon Kurkjian',
       'Dr. Douglas Diepenbrock', 'Dr. Ozan Sozer, M.D.',
       'Dr. David L. Stein', 'Dr. Bradley Calobrace',
       'Dr. David Kowalczyk',
       'Dr. Stephen P. Smith Jr. (Smith Facial Plastics)',
       'Dr. Steinwald', 'Dr. Bahman Guyuron', 'Dr. Alexander Donath',
       'Dr. Michael Horn', 'Dr. Bahman Naderi', 'Dr. Jonathan Kulbersh',
       'Dr. Samuel DeVictor', 'Dr. Stephen Prendiville, M.D.',
       'Dr. Sherif Sherris, MD', 'Dr. Mark Markarian', 'Dr. Adam Basner',
       'Dr. Hootan Daneshmand', 'Dr. Louis William Apostolakis, M.D.',
       'Dr. Anthony Tran', 'Dr. Christina Magill', 'Dr. Gallegos',
       'Dr. Shlomo Widder', 'Dr. Matthew Galardi', 'Dr. Maloney',
       'Dr. John F. Zavell, MD, FACS', 'Dr. Gerald Bock',
       "Dr. John J. O'Brien Jr., St. Petersburg Center for Plastic Surgery",
       'Dr. Wright', 'Dr. Santos', 'Dr. Navjot Singh', 'Dr. Tim Roham',
       'Dr. Eric Okamoto', 'Dr. Kenneth Bermudez', 'Dr. David Kent',
       'Dr. Melanie Carreon, M.D.', 'Dr. Rudy Coscia', 'Dr. Neil Zemmel',
       'Dr. Juan A. Ortiz', 'Dr. Matthew Lewis', 'Dr. S. Darrell Lee',
       'Dr. Raj Mohan', 'Dr. Richard M. Chierici', 'Dr. Paul Wigoda',
       'Dr. David Bottger, MD', 'Dr. Scott Rotatori', 'Dr. Anas Ayoub',
       'Dr. Gabriel H. Patino', 'Dr. Niamtu', 'Dr. Michael Gartner',
       'Dr. Thomas P. Sterry, MD', 'Dr. Kamran Khoobehi',
       'Dr. Michael Cash', 'Dr. Mesna', 'Dr. Bonness',
       'Dr. Roberto Lachica at The Langsdon Clinic', 'Dr. David Janssen',
       'Dr. Rowley, Rowley Plastic Surgery', 'Dr. Saul A. Hurvitz',
       'Dr. Jacobson at Jacobson Cosmetic Surgery', 'Dr. Stephen Miller',
       'Laredo Wellness and Aesthetics',
       'Dr. Hlavacek at Kansas City Surgical Arts', 'Dr. Sophia Kirk',
       'Dr. Cruise', 'Dr. Zollman of Zollman Plastic Surgery',
       'Dr. James Y. Fu, MD', 'Dr. George Avana', 'Dr. Shahin Ghadir',
       'Dr. Collier Pace', 'Dr. Raja Mohan', 'Dr. Mark A. Chin',
       'Dr. Steele',
       'Dr. Diepenbrock (Diepenbrock Facial Cosmetic Surgery)',
       'Dr. Frank Agullo, MD', 'Dr. Eric C. Polk', 'Dr. Lytle',
       'Dr. Jeff Russell', 'Dr. J. Keith Rose, MD', 'Dr. Zochowski',
       'Dr. Aaron D. Smith', 'Dr. Gregory M. Fedele, MD',
       'Dr. Matt Goldschmidt', 'Dr. Laurie A. Casas', 'Dr. Carney',
       'Dr. Joel Beck', 'Dr. Olson, Advanced Plastic Surgery Institute',
       'Dr. Lorraine Golosow, MD', 'Dr. Ricardo L. Rodriguez, MD',
       'Dr. Hootan Daneshmand, MD at Silhouette Plastic Surgery Institute',
       'Dr. Justin West, MD', 'Modern Surgical Arts of Denver & Aurora',
       'Dr. James Lee, MD', 'Dr. Jonathan Hermosa',
       'Dr. Michael Schoenfeld', 'Dr. Joe Choe', 'Dr. Angelo Cuzalina',
       'Dr. Charles Perry', 'Dr. John B. Copeland', 'Dr. Craig Jonov',
       'Dr. Roham Mozaffari of Roham Advanced Laser & Cosmetic Surgery',
       'Dr. Arash Maan', 'Dr. Larry Fan', 'Alexander Cosmetic Surgery',
       'Dr. David Gervais', 'Dr. Robert Hardesty', 'Dr. Mark Zinsser',
       'Dr. Kyle Yamamoto', 'Dr. Joel P. Stein', 'Dr. James Aycock',
       'Dr. Avron Lipschitz', 'Dr. Brobst', 'Dr. Paul Leong',
       'Dr. Joel E. Pontell, MD', 'Dr. Gross', 'Dr. Popp', 'Dr. Shadfar',
       'Dr. Moulton-Barrett', 'Dr. Jeffrey Roth', 'Dr. Jaehak Kim',
       'Dr. Pedy Ganchi', 'Dr. Shaun Parson', 'Dr. Richard Moses',
       'Dr. Mary O’Brien', 'Dr. Campbell at Quintessa',
       'Dr. Laris, Phoenix Skin', 'Dr. Phillip R. Langsdon, MD',
       'Dr. Schmid, Lubbock Plastic Surgery Institute',
       'Dr. Gerald O’Daniel', 'Dr. Dan Mills',
       'Dr. Jessica Jacobson DO, FAACS', 'Dr. Marco R. Avila, MD',
       'Monarch Plastic Surgery', 'Dr. Michael Kopelman',
       'Dr. John G. Csikai',
       'Dr. David Liland, MD, FACS (Dallas, near Irving)',
       'Dr. Goretti Ho Taghva', 'Dr. Stacey Wagner',
       'Dr. Michael Pasquale', 'Dr. Armando Soto', 'Dr. Eric Yavrouian',
       'Dr. Farris Plastic Surgery', 'Dr. Ken Smart',
       'Dr. John F. Burnett, MD', 'Dr. Robert G. Anderson',
       'Dr. Ryan Diepenbrock', 'Dr. Marco A. Gonzalez, MD',
       'Dr. Mark S. Codner, MD', 'Dr. Jason Lichten',
       'Dr. Alexander S. Donath', 'Dr. Ronald J. Edelson, MD',
       'Northwestern Plastic Surgery', 'Dr. Jae Kim', 'Dr. Todd Freeman',
       'Dr. Todd Hobgood, MD', 'Dr. Todd B. Koch',
       'Idaho Eyelid & Facial Plastic Surgery', 'Dr. Ronald Schuster',
       'Dr. Farzin Kerendian', 'Dr. Holzman (Holzman Plastic Surgery)',
       'Dr. Steven Camp, MD', 'Dr. Daniel Suver, MD, FACS',
       'Dr. Daniel Mills', 'Dr. Brent Sundin', 'Dr. Brenda Schiesel, MD',
       'Dr. Sanchez-Navarro', 'Dr. Frank Barone',
       'A leading breast reduction surgeon at Beautologie Cosmetic Surgery & Medical Aesthetics',
       'Dr. Jeffrey H. Barnett', 'Dr. Sanniec', 'Dr. Orna Fisher',
       'Dr. Vincent Marin', 'Dr. Michael Ablavsky', 'Dr. David Thao',
       'Dr. Lewis at Lewis Plastic Surgery',
       'Dr. McCormack and Dr. Joslyn (Reno Tahoe Plastic Surgery)',
       'North Raleigh Plastic Surgery', 'Dr. Austin Hayes, MD',
       'Dr. David Lickstein', 'Dr. Steven Camp', 'Dr. Theodore Foley',
       'Dr. Steven Turkeltaub', 'Dr. Alex Ayoub',
       'Surgeon at 9020 E. Reno Avenue, Floor 2, OKC (5.0 rating on MDsave)',
       'Dr. Patino', 'Dr. Frank L. Stile', 'Dr. Dennis K. Hammond',
       'Dr. Spiro', 'Dr. Richard H. Baxter',
       'Dr. Randy Sadeghi, MD at Sadeghi Plastic Surgery',
       'Dr. Joshua Greenwald',
       'Board-certified surgeons at Minneapolis Plastic Surgery, LTD',
       'Dr. Robert Bonness', 'Dr. Jason L. Marks',
       'Dr. Mark Plauche at NuBody Concepts, Memphis', 'Dr. Rowley',
       'Dr. Aaron Calobrace', 'Dr. Keith A. Hurvitz',
       'Dr. David Jacobson', 'Alamo Plastic Surgery', 'Dr. Jack Peterson',
       'Dr. Alexis Parcells, MD, New Jersey', 'Dr. Sofia Kirk',
       'Dr. Lawrence R. Farris, MD', 'Dr. Karen Leong',
       'The Gillian Institute (Indy Plastic Surgery)',
       'Dr. Tal T Roudner, MD', 'Dr. David Bowers', 'Dr. Ara K. Vartany',
       'Dr. Gawley', 'Dr. Ken Smart, MD', 'Dr. Sian',
       'Aspire Plastic Surgery',
       'Duke University Health System plastic surgeons',
       'Dr. Scott Brenman, MD', 'Dr. Anne Taylor',
       'Dr. Jessica R. Sherry', 'Dr. Husni', 'Dr. Donna Krummen',
       'Dr. Jonathan Eastlack',
       'Dr. Julia C. Stevenson, MD (Cardinal Plastic Surgery)',
       'Dr. G. Laurie Casas at GH Surgery, Charlotte', 'Dr. Daniel Olson',
       'Dr. Davek Sharma', 'Dr. James Quatela', 'Dr. Sean Doherty, MD',
       'Dr. John D. Wigod', 'Dr. Sarah Mess',
       'Dr. Stephen Mitts, Mitts Plastic Surgery, Bakersfield',
       'Dr. Aisha D. White', 'Dr. Jennifer Emmett, MD',
       'Plastic Surgeons of Alaska',
       'Dr. Miguel Gallegos, Hermosa Plastic Surgery',
       'Dr. Galardi, Galardi | Bowen Plastic Surgery', 'Dr. Tim R. Love',
       'Dr. Julian Guerra', 'Beautologie Stockton',
       "Dr. John J. O'Brien Jr.",
       'Dr. Copeland, Copeland Cosmetic Surgery',
       'Dr. Kris Day at Pacific Sound Plastic Surgery',
       'Dr. Kevin Parson', 'Dr. Michael A. Jazayeri, M.D.', 'Dr. Fan',
       'Dr. Waltzman', 'Dr. Heather Rocheford',
       'Dr. Sundin, Virginia Institute of Plastic Surgery',
       'Dr. James E. Murphy', 'Dr. Glenn Lyle', 'Dr. Michael Bohley',
       'Dr. Brian Lee', 'Dr. Lorelei Grunwaldt', 'Dr. Ricardo Guerra',
       'Dr. Bottger', 'Dr. Kamran Azad', 'Dr. Mohamed Ayoub',
       'Dr. Hayley Brown', 'Dr. Lukas N. Troell', 'Dr. Robyn Moses',
       'Dr. Brian P. Tierney',
       'Dr. Butz and Dr. Thayer at Quintessa, Milwaukee', 'Dr. Guerra',
       'Dr. Scott Turner', 'Dr. Troell', 'Dr. Kipp S. Towne',
       'Dr. Josh Waltzman', 'Dr. Mitchell',
       'Plastic Surgeons of Lexington', 'Dr. Kush Pancholi',
       'Dr. Lance Troell, MD',
       'Dr. Levi Young, Advanced Cosmetic Surgery KC', 'Dr. James Hardy',
       'Dr. Jerry W. Troell in Irving', 'Dr. Conrad Tirre',
       'Dr. Daniel Barrett, MD', 'Dr. Himansu Shah, MD, FACS',
       'Dr. H. Christopher Coley', 'Dr. Vartan Mardirossian, MD',
       'Dr. Richard Guerra', 'Dr. Kunkel',
       'Dr. Joe, Plastic Surgery Innovations, Fort Wayne',
       'Dr. Zachary Tannan, MD (Raleigh)', 'Dr. Andrew Lofman',
       'Dr. Adam Levy, MD', 'Dr. Michael Donaldson',
       'Institute of Plastic Surgery', 'Dr. David T. Troell',
       'Eastlake Cosmetic Surgery', 'Dr. William Troell',
       'Dr. Erik J. Miles', 'Dr. Guerra at Guerra Plastic Surgery Center',
       'Dr. Kent V. Hasen', 'Dr. Andrew Giacobbe', 'Dr. Sean Doherty',
       'Dr. Sean Younai', 'Dr. Steven Thompson at Modern Surgical Arts',
       'Dr. Thomas Kramer', 'Dr. Paul Gallegos'], dtype=object)

In [136]:
crit = ~df['Top Rated Surgeon'].str.contains('Dr|MD', na=False) #Criteria of exclusion of all variable in Top Rated Surgeon that has MD or Dr in it
institutions_df = df.loc[crit] #Define dataframe
institutions_df.head()

,City,Procedure,Number of Surgeons,Price Range,Average Price ($),Top Rated Surgeon,More Information
32,Atlanta,Liposuction,23,"$750 to $5,500",3100.0,Plastic Surgery Center of the South,https://www.aestheticmatch.com/cities/atlanta
38,Winston-Salem,Breast Reduction,39,"$10,000 – $11,000",10800.0,Salem Plastic Surgery,https://www.aestheticmatch.com
107,Greensboro,Tummy Tuck,227,"$6,500 - $11,000",8209.0,Award-winning surgeons at H/K/B Cosmetic Surge...,https://www.aestheticmatch.com
162,Port St. Lucie,Nose Plastic Surgery (Rhinoplasty),79,"$2,500 to $15,000+",7200.0,Lee Plastic Surgery,https://www.aestheticmatch.com
195,Honolulu,Nose Plastic Surgery (Rhinoplasty),26,"$2,000 - $12,000",6200.0,Athena Clinic,https://www.aestheticmatch.com

In [137]:
institutions_df.shape #How many rows and columns does the new dataframe have

(24, 7)

###Creating or Updating values in a dataframe

####Renaming a column

We did this before. Names can be replaced of individual columns with the `rename()` method using a dictionary. Below we change Number of surgeons to No. of surgeons. For changes to be permanent we need to change the default inplace= argument value to True.

In [138]:
df.rename(columns={'Number of Surgeons':'No. of Surgeons'}, inplace=True) #Replacing the name of the column
df.head()

,City,Procedure,No. of Surgeons,Price Range,Average Price ($),Top Rated Surgeon,More Information
0,Tampa,Tummy Tuck,419,"$7,000 to $14,000",7600.0,Dr. John Roach,https://www.aestheticmatch.com/cities/tampa
1,Tampa,Breast Reduction,169,"$6,000 to $11,200",11350.0,"Dr. Traci Temmen, MD",https://www.aestheticmatch.com/cities/tampa
2,Tampa,Liposuction,156,"$4,000 to $11,000",8000.0,Dr. Traci Temmen,https://www.aestheticmatch.com/cities/tampa
3,Tampa,Breast Implants,152,"$4,500 - $6,500",5700.0,Dr. Jaime Perez,https://www.aestheticmatch.com/cities/tampa
4,Tampa,Facelift,147,"$8,900 - $17,000",12300.0,"Dr. Demetri Arnaoutakis, MD",https://www.aestheticmatch.com/cities/tampa

####Add numerical values to every value in a column

Let's say that there is a new taxation on the Average Price ($) of 12%, and therefore every value should be increased by 12%

In [139]:
df['Average Price ($)'] = df['Average Price ($)'].apply(lambda x: x*1.12) #Applying the lambda function to the column
df.head()

,City,Procedure,No. of Surgeons,Price Range,Average Price ($),Top Rated Surgeon,More Information
0,Tampa,Tummy Tuck,419,"$7,000 to $14,000",8512.0,Dr. John Roach,https://www.aestheticmatch.com/cities/tampa
1,Tampa,Breast Reduction,169,"$6,000 to $11,200",12712.0,"Dr. Traci Temmen, MD",https://www.aestheticmatch.com/cities/tampa
2,Tampa,Liposuction,156,"$4,000 to $11,000",8960.0,Dr. Traci Temmen,https://www.aestheticmatch.com/cities/tampa
3,Tampa,Breast Implants,152,"$4,500 - $6,500",6384.0,Dr. Jaime Perez,https://www.aestheticmatch.com/cities/tampa
4,Tampa,Facelift,147,"$8,900 - $17,000",13776.0,"Dr. Demetri Arnaoutakis, MD",https://www.aestheticmatch.com/cities/tampa

###Changing columns (with some data cleaning)

I want to create 2 sets of columns stating minimum price and maximum price using the information of the Price Range. But here I find a problem that needs data cleaning because the Price Range columns have inconsistent string formats: $, commas, different separators (to; -), ocassional trailing +.

In [140]:
#1. Clean unwanted characters
df['Price Range'] = (
    df['Price Range']
    .astype(str)  # Convert to string to handle non-string or NaN values
    .str.replace(r'[\$,]', '', regex=True)  # remove $ and ,
    .str.replace(r'\+', '', regex=True) # remove +
    .str.strip() # remove trailing spaces
    .str.lower()  # Convert to lowercase for consistent 'to' replacement
)

#2. Split into min and max (handling 'to' and '-')
df[['Minimum Price ($)', 'Maximum Price ($)']] = (
    df['Price Range']
    .str.replace(r'\s*to\s*', '-', regex=True)  # Standardize 'to' (case-insensitive, with spaces) / regex=False because I am replacing plain text to text, not like before the pattern [\$,] that needs regex to be True
    .str.replace(r'\s*-\s*', '-', regex=True)  # Standardize '-' (remove extra spaces)
    .str.split ('-', expand=True) #Split into two columns
)

# 3. Clean up split columns and convert to numeric
# Strip spaces from split columns
df['Minimum Price ($)'] = df['Minimum Price ($)'].str.strip()
df['Maximum Price ($)'] = df['Maximum Price ($)'].str.strip()

# Convert to numeric, coercing errors to NaN
df['Minimum Price ($)'] = pd.to_numeric(df['Minimum Price ($)'], errors='coerce')
df['Maximum Price ($)'] = pd.to_numeric(df['Maximum Price ($)'], errors='coerce')

# Handle invalid or missing prices
# Example: Replace NaN with 0 or drop rows with NaN
df['Minimum Price ($)'] = df['Minimum Price ($)'].fillna(0).astype(int)
df['Maximum Price ($)'] = df['Maximum Price ($)'].fillna(0).astype(int)

# Validate prices (e.g., ensure Minimum <= Maximum and non-negative)
df = df[df['Minimum Price ($)'] >= 0]  # Remove negative minimum prices
df = df[df['Maximum Price ($)'] >= 0]  # Remove negative maximum prices
df = df[df['Minimum Price ($)'] <= df['Maximum Price ($)']]  # Ensure min <= max

#4. Drop intermediate cleaned column (to erase the column 'Price Range' as it would not longer be needed and return a new dataframe)
df.drop('Price Range', axis=1, inplace=True)

df.head()

,City,Procedure,No. of Surgeons,Average Price ($),Top Rated Surgeon,More Information,Minimum Price ($),Maximum Price ($)
0,Tampa,Tummy Tuck,419,8512.0,Dr. John Roach,https://www.aestheticmatch.com/cities/tampa,7000,14000
1,Tampa,Breast Reduction,169,12712.0,"Dr. Traci Temmen, MD",https://www.aestheticmatch.com/cities/tampa,6000,11200
2,Tampa,Liposuction,156,8960.0,Dr. Traci Temmen,https://www.aestheticmatch.com/cities/tampa,4000,11000
3,Tampa,Breast Implants,152,6384.0,Dr. Jaime Perez,https://www.aestheticmatch.com/cities/tampa,4500,6500
4,Tampa,Facelift,147,13776.0,"Dr. Demetri Arnaoutakis, MD",https://www.aestheticmatch.com/cities/tampa,8900,17000

After this, I noticed that the 2 columns were added at last of the columns and i would like them to be placed bwteen Average Price ($) and Top rated Surgeon

In [141]:
# Reordering the columns
desired_columns = [
    'City',
    'Procedure',
    'No. of Surgeons',
    'Average Price ($)',
    'Minimum Price ($)',  # Move here
    'Maximum Price ($)',  # Move here
    'Top Rated Surgeon',
    'More Information'
]

# Reorder the DataFrame columns
df = df[desired_columns]

# Display first few rows to confirm
df.head()

,City,Procedure,No. of Surgeons,Average Price ($),Minimum Price ($),Maximum Price ($),Top Rated Surgeon,More Information
0,Tampa,Tummy Tuck,419,8512.0,7000,14000,Dr. John Roach,https://www.aestheticmatch.com/cities/tampa
1,Tampa,Breast Reduction,169,12712.0,6000,11200,"Dr. Traci Temmen, MD",https://www.aestheticmatch.com/cities/tampa
2,Tampa,Liposuction,156,8960.0,4000,11000,Dr. Traci Temmen,https://www.aestheticmatch.com/cities/tampa
3,Tampa,Breast Implants,152,6384.0,4500,6500,Dr. Jaime Perez,https://www.aestheticmatch.com/cities/tampa
4,Tampa,Facelift,147,13776.0,8900,17000,"Dr. Demetri Arnaoutakis, MD",https://www.aestheticmatch.com/cities/tampa

In [142]:
# I want set values in Average Price ($), Minimum Price ($) and Maximum Price ($) as floats that contains 2 decimals
df['Average Price ($)'] = df['Average Price ($)'].astype(float).round(2)
df['Minimum Price ($)'] = df['Minimum Price ($)'].astype(float).round(2)
df['Maximum Price ($)'] = df['Maximum Price ($)'].astype(float).round(2)

df.head()

,City,Procedure,No. of Surgeons,Average Price ($),Minimum Price ($),Maximum Price ($),Top Rated Surgeon,More Information
0,Tampa,Tummy Tuck,419,8512.0,7000.0,14000.0,Dr. John Roach,https://www.aestheticmatch.com/cities/tampa
1,Tampa,Breast Reduction,169,12712.0,6000.0,11200.0,"Dr. Traci Temmen, MD",https://www.aestheticmatch.com/cities/tampa
2,Tampa,Liposuction,156,8960.0,4000.0,11000.0,Dr. Traci Temmen,https://www.aestheticmatch.com/cities/tampa
3,Tampa,Breast Implants,152,6384.0,4500.0,6500.0,Dr. Jaime Perez,https://www.aestheticmatch.com/cities/tampa
4,Tampa,Facelift,147,13776.0,8900.0,17000.0,"Dr. Demetri Arnaoutakis, MD",https://www.aestheticmatch.com/cities/tampa

In [143]:
df.tail()

,City,Procedure,No. of Surgeons,Average Price ($),Minimum Price ($),Maximum Price ($),Top Rated Surgeon,More Information
595,Aurora,Breast Implants,3,10472.0,8800.0,9700.0,Dr. Steven Thompson at Modern Surgical Arts,https://www.aestheticmatch.com
596,Arlington,Breast Implants,7,7683.2,6725.0,16500.0,Dr. Vishnu Rumalla,https://www.aestheticmatch.com
597,Anchorage,Breast Implants,6,8288.0,3800.0,18465.0,Dr. Thomas Kramer,https://www.aestheticmatch.com
598,Anaheim,Breast Implants,407,9184.0,0.0,0.0,"Dr. Saba Motakef, MD",https://www.aestheticmatch.com
599,Albuquerque,Breast Implants,11,6272.0,4600.0,7200.0,Dr. Paul Gallegos,https://www.aestheticmatch.com

###Create a categorical variable from numerical data (inserting a new column)

In [144]:
df['No. of Surgeons'].dtypes

dtype('int64')

The column 'No. of Surgeons' has integer type as data values. I would like to create a column at the right of it that says a categorical variable. If the number is < 20, the data should read 'Low'; 20-150, 'Intermediate'; >150, 'High'

In [145]:
# Create a categorical column right next to 'No. of Surgeons'
bins = [-float('inf'), 19, 150, float('inf')] # Define ranges: <20, 20-150, >150
labels = ['Low', 'Intermediate', 'High']
df['Surgeon Volume'] = pd.cut(
    df['No. of Surgeons'],
    bins=bins,
    labels=labels,
    right=False,
    include_lowest=True
)

#Reorder again the columns
desired_columns = [
    'City',
    'Procedure',
    'No. of Surgeons',
    'Surgeon Volume',
    'Average Price ($)',
    'Minimum Price ($)',
    'Maximum Price ($)',
    'Top Rated Surgeon',
    'More Information'
]

df = df[desired_columns]

df.head()

,City,Procedure,No. of Surgeons,Surgeon Volume,Average Price ($),Minimum Price ($),Maximum Price ($),Top Rated Surgeon,More Information
0,Tampa,Tummy Tuck,419,High,8512.0,7000.0,14000.0,Dr. John Roach,https://www.aestheticmatch.com/cities/tampa
1,Tampa,Breast Reduction,169,High,12712.0,6000.0,11200.0,"Dr. Traci Temmen, MD",https://www.aestheticmatch.com/cities/tampa
2,Tampa,Liposuction,156,High,8960.0,4000.0,11000.0,Dr. Traci Temmen,https://www.aestheticmatch.com/cities/tampa
3,Tampa,Breast Implants,152,High,6384.0,4500.0,6500.0,Dr. Jaime Perez,https://www.aestheticmatch.com/cities/tampa
4,Tampa,Facelift,147,Intermediate,13776.0,8900.0,17000.0,"Dr. Demetri Arnaoutakis, MD",https://www.aestheticmatch.com/cities/tampa

In [146]:
# Count the number of occurrences for each category in 'Surgeon Volume'
surgeon_volume_counts = df['Surgeon Volume'].value_counts()

# Define the desired order of categories
category_order = ['Low', 'Intermediate', 'High']

# Reindex the Series to the desired order
surgeon_volume_counts = surgeon_volume_counts.reindex(category_order)

# Display the counts
print("Counts of each Surgeon Volume category:")
display(surgeon_volume_counts)

Counts of each Surgeon Volume category:

Surgeon Volume
Low             195
Intermediate    268
High            135
Name: count, dtype: int64

###Sorting

We can sort data alphabetically

In [147]:
df.sort_values(by = 'City')

,City,Procedure,No. of Surgeons,Surgeon Volume,Average Price ($),Minimum Price ($),Maximum Price ($),Top Rated Surgeon,More Information
599,Albuquerque,Breast Implants,11,Low,6272.0,4600.0,7200.0,Dr. Paul Gallegos,https://www.aestheticmatch.com
231,Albuquerque,Nose Plastic Surgery (Rhinoplasty),17,Low,5936.0,5000.0,10000.0,Dr. Gallegos,https://www.aestheticmatch.com
323,Albuquerque,Liposuction,8,Low,7616.0,3500.0,8000.0,Dr. Jonathan Hermosa,https://www.aestheticmatch.com
415,Albuquerque,Facelift,8,Low,9632.0,6250.0,10000.0,Dr. Miguel Gallegos,https://www.aestheticmatch.com
140,Albuquerque,Tummy Tuck,71,Intermediate,8792.0,7600.0,8000.0,Dr. Miguel Gallegos,https://www.aestheticmatch.com
...,...,...,...,...,...,...,...,...,...
38,Winston-Salem,Breast Reduction,39,Intermediate,12096.0,0.0,0.0,Salem Plastic Surgery,https://www.aestheticmatch.com
40,Winston-Salem,Facelift,29,Intermediate,16408.0,14000.0,16000.0,Dr. Sanjay Daluvoy,https://www.aestheticmatch.com
41,Winston-Salem,Liposuction,23,Intermediate,5824.0,3000.0,8000.0,Dr. Gilson J. Kingman,https://www.aestheticmatch.com
42,Winston-Salem,Breast Implants,24,Intermediate,8590.4,7500.0,8000.0,Dr. Charles Milliken,https://www.aestheticmatch.com
46,Winston-Salem,Nose Plastic Surgery (Rhinoplasty),41,Intermediate,9520.0,6000.0,15000.0,"Dr. Scott L. Tucker, MD",https://www.aestheticmatch.com

The alphabetical order can be reversed by using the `acending=False`.

In [148]:
df.sort_values(by = 'City', ascending=False)

,City,Procedure,No. of Surgeons,Surgeon Volume,Average Price ($),Minimum Price ($),Maximum Price ($),Top Rated Surgeon,More Information
42,Winston-Salem,Breast Implants,24,Intermediate,8590.4,7500.0,8000.0,Dr. Charles Milliken,https://www.aestheticmatch.com
38,Winston-Salem,Breast Reduction,39,Intermediate,12096.0,0.0,0.0,Salem Plastic Surgery,https://www.aestheticmatch.com
36,Winston-Salem,Tummy Tuck,173,High,10192.0,6000.0,12000.0,"Dr. Andrew M. Schneider, M.D., F.A.C.S.",https://www.aestheticmatch.com
46,Winston-Salem,Nose Plastic Surgery (Rhinoplasty),41,Intermediate,9520.0,6000.0,15000.0,"Dr. Scott L. Tucker, MD",https://www.aestheticmatch.com
40,Winston-Salem,Facelift,29,Intermediate,16408.0,14000.0,16000.0,Dr. Sanjay Daluvoy,https://www.aestheticmatch.com
...,...,...,...,...,...,...,...,...,...
140,Albuquerque,Tummy Tuck,71,Intermediate,8792.0,7600.0,8000.0,Dr. Miguel Gallegos,https://www.aestheticmatch.com
231,Albuquerque,Nose Plastic Surgery (Rhinoplasty),17,Low,5936.0,5000.0,10000.0,Dr. Gallegos,https://www.aestheticmatch.com
507,Albuquerque,Breast Reduction,19,Intermediate,7392.0,4887.0,8431.0,"Dr. Miguel Gallegos, Hermosa Plastic Surgery",https://www.aestheticmatch.com
323,Albuquerque,Liposuction,8,Low,7616.0,3500.0,8000.0,Dr. Jonathan Hermosa,https://www.aestheticmatch.com
599,Albuquerque,Breast Implants,11,Low,6272.0,4600.0,7200.0,Dr. Paul Gallegos,https://www.aestheticmatch.com

We can sort more than one column at a time

In [149]:
df.sort_values(by = ['City','Average Price ($)'], ascending=[True,False]) #Means that 'City' will go from A to Z; and 'Average Price ($)', from the highest to lowest

,City,Procedure,No. of Surgeons,Surgeon Volume,Average Price ($),Minimum Price ($),Maximum Price ($),Top Rated Surgeon,More Information
415,Albuquerque,Facelift,8,Low,9632.0,6250.0,10000.0,Dr. Miguel Gallegos,https://www.aestheticmatch.com
140,Albuquerque,Tummy Tuck,71,Intermediate,8792.0,7600.0,8000.0,Dr. Miguel Gallegos,https://www.aestheticmatch.com
323,Albuquerque,Liposuction,8,Low,7616.0,3500.0,8000.0,Dr. Jonathan Hermosa,https://www.aestheticmatch.com
507,Albuquerque,Breast Reduction,19,Intermediate,7392.0,4887.0,8431.0,"Dr. Miguel Gallegos, Hermosa Plastic Surgery",https://www.aestheticmatch.com
599,Albuquerque,Breast Implants,11,Low,6272.0,4600.0,7200.0,Dr. Paul Gallegos,https://www.aestheticmatch.com
...,...,...,...,...,...,...,...,...,...
38,Winston-Salem,Breast Reduction,39,Intermediate,12096.0,0.0,0.0,Salem Plastic Surgery,https://www.aestheticmatch.com
36,Winston-Salem,Tummy Tuck,173,High,10192.0,6000.0,12000.0,"Dr. Andrew M. Schneider, M.D., F.A.C.S.",https://www.aestheticmatch.com
46,Winston-Salem,Nose Plastic Surgery (Rhinoplasty),41,Intermediate,9520.0,6000.0,15000.0,"Dr. Scott L. Tucker, MD",https://www.aestheticmatch.com
42,Winston-Salem,Breast Implants,24,Intermediate,8590.4,7500.0,8000.0,Dr. Charles Milliken,https://www.aestheticmatch.com
41,Winston-Salem,Liposuction,23,Intermediate,5824.0,3000.0,8000.0,Dr. Gilson J. Kingman,https://www.aestheticmatch.com

The .sort_value() method does not make permanent changes to the dataframe, unless the argument inplace (which is set to False by default) is set to True.

As I don't want to make it as a permanent change, I will just recall .head() to see the original order

In [150]:
df.head()

,City,Procedure,No. of Surgeons,Surgeon Volume,Average Price ($),Minimum Price ($),Maximum Price ($),Top Rated Surgeon,More Information
0,Tampa,Tummy Tuck,419,High,8512.0,7000.0,14000.0,Dr. John Roach,https://www.aestheticmatch.com/cities/tampa
1,Tampa,Breast Reduction,169,High,12712.0,6000.0,11200.0,"Dr. Traci Temmen, MD",https://www.aestheticmatch.com/cities/tampa
2,Tampa,Liposuction,156,High,8960.0,4000.0,11000.0,Dr. Traci Temmen,https://www.aestheticmatch.com/cities/tampa
3,Tampa,Breast Implants,152,High,6384.0,4500.0,6500.0,Dr. Jaime Perez,https://www.aestheticmatch.com/cities/tampa
4,Tampa,Facelift,147,Intermediate,13776.0,8900.0,17000.0,"Dr. Demetri Arnaoutakis, MD",https://www.aestheticmatch.com/cities/tampa

####Largest and lowest numerical values

In [151]:
df.nlargest(15,'No. of Surgeons') #The 15 largest values of No. of Surgeons

,City,Procedure,No. of Surgeons,Surgeon Volume,Average Price ($),Minimum Price ($),Maximum Price ($),Top Rated Surgeon,More Information
55,St. Petersburg,Tummy Tuck,1878,High,10251.36,7500.0,11350.0,Dr. John J. O’Brien,https://www.aestheticmatch.com
56,St. Louis,Tummy Tuck,1878,High,14392.00,11000.0,17000.0,"Dr. Paul Rottler, MD",https://www.aestheticmatch.com
83,New York,Tummy Tuck,1733,High,16161.60,5000.0,16500.0,"Dr. Matthew Schulman, M.D.",https://www.aestheticmatch.com
139,Anaheim,Tummy Tuck,1111,High,9654.40,6000.0,12000.0,"Dr. Saba Motakef, MD",https://www.aestheticmatch.com
59,Santa Ana,Tummy Tuck,1102,High,13154.40,8000.0,20000.0,Dr. Wayne Yamahata,https://www.aestheticmatch.com
12,Los Angeles,Tummy Tuck,1081,High,17225.60,4000.0,20000.0,Dr. Stephen Bresnick,https://www.aestheticmatch.com/cities/los-angeles
93,Long Beach,Tummy Tuck,1060,High,10976.00,6000.0,12000.0,Dr. Naim,https://www.aestheticmatch.com
422,St. Petersburg,Breast Reduction,809,High,10864.00,2900.0,11200.0,Dr. Traci Temmen,https://www.aestheticmatch.com
423,St. Louis,Breast Reduction,809,High,10432.80,0.0,0.0,Dr. Wright,https://www.aestheticmatch.com
466,Jersey City,Breast Reduction,800,High,11088.00,0.0,0.0,"Dr. Alexis Parcells, MD, New Jersey",https://www.aestheticmatch.com
146,St. Petersburg,Nose Plastic Surgery (Rhinoplasty),765,High,9408.00,5000.0,18000.0,Dr. Kevin Caceres,https://www.aestheticmatch.com
147,St. Louis,Nose Plastic Surgery (Rhinoplasty),765,High,9128.00,3500.0,14000.0,"Dr. Brian Ridenour, MD",https://www.aestheticmatch.com
190,Jersey City,Nose Plastic Surgery (Rhinoplasty),758,High,16016.00,6000.0,50000.0,Dr. Robert Morin,https://www.aestheticmatch.com
238,St. Petersburg,Liposuction,701,High,6104.00,3500.0,7500.0,"Dr. John J. O'Brien Jr., St. Petersburg Center...",https://www.aestheticmatch.com
239,St. Louis,Liposuction,701,High,3864.00,0.0,0.0,Dr. Wright,https://www.aestheticmatch.com

In [152]:
df.nsmallest(10,'No. of Surgeons') #The 10 smallest values of No. of Surgeons

,City,Procedure,No. of Surgeons,Surgeon Volume,Average Price ($),Minimum Price ($),Maximum Price ($),Top Rated Surgeon,More Information
135,Austin,Tummy Tuck,0,Low,13664.0,8000.0,15000.0,Dr. Aisha White,https://www.aestheticmatch.com
188,Laredo,Nose Plastic Surgery (Rhinoplasty),0,Low,8736.0,4000.0,16000.0,Dr. Jose Barrera,https://www.aestheticmatch.com
202,Frisco,Nose Plastic Surgery (Rhinoplasty),0,Low,12488.0,7000.0,20000.0,Dr. Sean Hill,https://www.aestheticmatch.com
226,Austin,Nose Plastic Surgery (Rhinoplasty),0,Low,17796.8,0.0,0.0,"Dr. Louis William Apostolakis, M.D.",https://www.aestheticmatch.com
250,Richmond,Liposuction,0,Low,4144.0,2000.0,7500.0,Dr. Neil Zemmel,https://www.aestheticmatch.com
280,Laredo,Liposuction,0,Low,14448.0,10000.0,16000.0,Laredo Wellness and Aesthetics,https://www.aestheticmatch.com
289,Henderson,Liposuction,0,Low,13664.0,3900.0,20000.0,Dr. Shahin Ghadir,https://www.aestheticmatch.com
292,Gilbert,Liposuction,0,Low,13272.0,2000.0,18000.0,"Dr. Jude LaBarbera, MD",https://www.aestheticmatch.com
294,Frisco,Liposuction,0,Low,4592.0,3600.0,8500.0,Dr. Raja Mohan,https://www.aestheticmatch.com
318,Austin,Liposuction,0,Low,6608.0,3000.0,9800.0,"Dr. Justin West, MD",https://www.aestheticmatch.com

###Missing Values

Missing values are represented by `nan` that means Not a Number values

We can find missing data from each row by using `.isna()` method, and will return `true` or `false` depending if they have missing values or not

In [153]:
df.isna() #Check the dataframe in general to see a Nan value which there is not apparently

,City,Procedure,No. of Surgeons,Surgeon Volume,Average Price ($),Minimum Price ($),Maximum Price ($),Top Rated Surgeon,More Information
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
595,False,False,False,False,False,False,False,False,False
596,False,False,False,False,False,False,False,False,False
597,False,False,False,False,False,False,False,False,False
598,False,False,False,False,False,False,False,False,False
599,False,False,False,False,False,False,False,False,False

In [154]:
df.isna().sum() #Here we see that the sum of all Nan values, which is zero; meaning that there are not missing values

City                 0
Procedure            0
No. of Surgeons      0
Surgeon Volume       0
Average Price ($)    0
Minimum Price ($)    0
Maximum Price ($)    0
Top Rated Surgeon    0
More Information     0
dtype: int64

Of course, this is a coincidence because our dataset is acceptable with no missing values. But, I did some cleaning in the 'Changing columns' section. I replaced Nan values to 0 (zero), so I will need to identify the '0' that does not make sense to my dataset.

I am going to focus on the columns `Minimum Price ($)` and `Maximum Price ($)` based on `Average Price ($)`, because if I have a numerical value in `Average Price ($)` that is `> 0`, then it does not make sense that `Minimum Price ($)` and `Maximum Price ($)` = 0

In [155]:
# Minimum price ($) that are 0, but Average price ($) > 0
bad_min_price = df[(df['Minimum Price ($)'] == 0) & (df['Average Price ($)'] > 0)]
bad_min_price.head()

,City,Procedure,No. of Surgeons,Surgeon Volume,Average Price ($),Minimum Price ($),Maximum Price ($),Top Rated Surgeon,More Information
11,Miami,Nose Plastic Surgery (Rhinoplasty),289,High,9520.0,0.0,0.0,Dr. Anthony Bared,https://www.aestheticmatch.com/cities/miami
16,Los Angeles,Facelift,379,High,24080.0,0.0,0.0,Dr. Jay Calvert,https://www.aestheticmatch.com/cities/los-angeles
18,Houston,Tummy Tuck,105,Intermediate,13608.0,0.0,0.0,Dr. Christopher Patronella,https://www.aestheticmatch.com/cities/houston
25,Dallas,Facelift,6,Low,16968.0,0.0,0.0,Dr. David Liland,https://www.aestheticmatch.com/cities/dallas
31,Atlanta,Breast Reduction,39,Intermediate,11368.0,0.0,0.0,Dr. Richard J. Arslanian,https://www.aestheticmatch.com/cities/atlanta

In [156]:
bad_min_price.shape # Here we can see that there are 66 rows that follow this rule

(66, 9)

In [157]:
# Maximum price ($) that are 0, but Average price ($) > 0
bad_max_price = df[(df['Maximum Price ($)'] == 0) & (df['Average Price ($)'] > 0)]
bad_max_price.head()

,City,Procedure,No. of Surgeons,Surgeon Volume,Average Price ($),Minimum Price ($),Maximum Price ($),Top Rated Surgeon,More Information
11,Miami,Nose Plastic Surgery (Rhinoplasty),289,High,9520.0,0.0,0.0,Dr. Anthony Bared,https://www.aestheticmatch.com/cities/miami
16,Los Angeles,Facelift,379,High,24080.0,0.0,0.0,Dr. Jay Calvert,https://www.aestheticmatch.com/cities/los-angeles
18,Houston,Tummy Tuck,105,Intermediate,13608.0,0.0,0.0,Dr. Christopher Patronella,https://www.aestheticmatch.com/cities/houston
25,Dallas,Facelift,6,Low,16968.0,0.0,0.0,Dr. David Liland,https://www.aestheticmatch.com/cities/dallas
31,Atlanta,Breast Reduction,39,Intermediate,11368.0,0.0,0.0,Dr. Richard J. Arslanian,https://www.aestheticmatch.com/cities/atlanta

In [158]:
bad_max_price.shape # Here we can see that there are 66 rows that follow this rule

(66, 9)

####Methods to deal with missing values

There exists methods to deal with missing data from simple to complex that come with pros and cons. Deletions methods and Imputation methods.

#####Deletions Methods

Deletion of rows (Listwise deletion) and deletion of columns (Dropping variables). They are the easiest methods but can lead to a significant loss of valuable information and statistical power, especially if missing values are common.

To simply remove all the rows containig any missing data, use `.dropna()`, and to make the changes permanent to the dataframe use `inplace=True` argument.

Another argument is `axis=`. By default this is set to `0` or `index`, which indicates that we are interested in dropping rows.  When set to `1` or `columns`, columns will be dropped. We can focus which columns to include when checking for missing values `dataframe.dropna(subset=['Name of Column'])`

As stated before, these methods are not very reliable, so I am not going to use it.

#####Imputations methods

**Simple imputations:** Replaces missing values with the mean, median, or mode of that column.



*   **Mean Imputation:** Best for numerical values with a normal distribution and no significant otliers.
*   **Median Imputation:** For numerical data that is skewed or contains significant outliers.

*   **Mode Imputation:** A good approach for categorical variables

**Forward and backward fill:** Replaces missing values using the value from the previous observation (forward fill) or the next observation (backward fill). Ideal for time-series data, where you can assume that the value will remain constant over a short period. To fill the Nan data with another value use `.fillna()`, and then the argument `method=ffill` (forward fill) uses the previous valid value to replace the Nan, and `method=bfill` (backward fill) uses the next valid value.

*   dataframe['Column'].fillna(method='ffill')

**K-Nearest Neighbors (KNN) imputation:** Uses a specified number of "neighboring" observations to impute missing values based on similarity. For a missing value, it finds the 'k' closest data points in the dataset and uses a weighted average of their values to make a guess.
This is for complex analysis, and can handle both numerical and categorical data

**Advanced imputation:**

*   **Regression imputation:** Uses a regression model to predict missing values based on other variables in the dataset.
*   **Multiple Imputation by Chained Equations (MICE):** A sophisticated method that creates multiple imputed datasets.

Once a very rapid review of imputation, I will use simple imputation with median

In [159]:
#Median calculation for Minimum Price ($)
median_min_price = df.loc[df['Minimum Price ($)'] > 0, 'Minimum Price ($)'].median() # I used > 0 to exclude 0 from the median formula
median_min_price

6000.0

In [160]:
#Median calculation for Maximum Price ($)
median_max_price = df.loc[df['Maximum Price ($)'] > 0, 'Maximum Price ($)'].median() # I used > 0 to exclude 0 from the median formula
median_max_price

14000.0

In [161]:
#Replace zeros with the median (only when Avg > 0) for Minimum Price ($)
df.loc[(df['Minimum Price ($)'] == 0) & (df['Average Price ($)'] > 0), 'Minimum Price ($)'] = median_min_price

In [162]:
#Replace zeros with the median (only when Avg > 0) for Maximum Price ($)
df.loc[(df['Maximum Price ($)'] == 0) & (df['Average Price ($)'] > 0), 'Maximum Price ($)'] = median_max_price

In [163]:
(df['Minimum Price ($)'] == 0).sum() ##Checking how many 0 (the sum of 0) are there in the column

np.int64(0)

In [164]:
(df['Maximum Price ($)'] == 0).sum() ##Checking how many 0 (the sum of 0) are there in the column

np.int64(0)

Note: I could have done a better imputation by calculating the median based on the procedure (median of liposuction is not the same as rhinoplasty), and for this it would have been necessary to check which `0` or `Nan` corresponded to which specific procedure. But this was made for an example of imputations.

###Download cleaned file to computer

In [165]:
#Save dataframe as csv in Colab
df.to_csv('cleaned_data.csv', index=False) #index = False prevents pandas from writing row numbers into the file.

In [166]:
#Download csv to computer
from google.colab import files
files.download('cleaned_data.csv')